database: hsqldb

# Database Settings
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always

  # H2 Settings
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Settings
  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  logging:
    level:
      org:
        springframework.web: debug

  sql:
    init:
      schema-locations: classpath*:/${database}/schema.sql
      data-locations: classpath*:/${database}/data.sql
      platform: h2


springdoc:
  swagger-ui:
    path: /terra/swagger-ui
    display-request-duration: true
    groups-order: DESC
  # swagger 서버 주소
  serverInfo:
    host: http://localhost
    port: 8089
